apiVersion: v2
name: workload
description: A general-purpose kubernetes workload chart with batteries included

type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: Artem Yakimenko
    email: helm@temik.me
