apiVersion: v2
name: workload
description: A general-purpose kubernetes workload chart with batteries included

type: application
version: 1.4.3
appVersion: "1.4.3"

maintainers:
  - name: Artem Yakimenko
    email: helm@temik.me
