[tasks.build]
description = "Build the chart"
run = [
    'helm dependency update',
    'helm package -d pkg .'
]

[tasks.push]
description = "Push the chart to the repository"
run = "helm push pkg/*.tgz oci://ghcr.io/temikus/helm-charts"

[tasks.test]
description = "Test the chart"
run = "helm unittest ."

[tasks.update-snapshot]
description = "Test the chart"
run = "helm unittest -u ."

[tasks.lint]
description = "Lint the chart"
run = "helm lint ."
