[tasks.build]
description = "Build the chart"
depends = ["clean"]
run = [
    'helm package -d pkg .'
]

[tasks.push]
description = "Push the chart to the repository (only if version doesn't exist)"
run = "./scripts/helm_push.sh"

[tasks.test]
description = "Test the chart"
run = "helm unittest ."

[tasks.update-snapshot]
description = "Test the chart"
run = "helm unittest -u ."

[tasks.lint]
description = "Lint the chart"
run = "helm lint ."

[tasks.clean]
description = "Clean the pkg and charts directories"
run = "rm -rf pkg/* charts/*"
