{{- range .Values.ports }}
  {{- if .service }}
    {{- if eq .service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  {{/* Prefer override if set */}}
  {{- if .service.nameOverride -}}
  name: {{ .service.nameOverride }}
  {{/* Set service name if set*/}}
  {{- else if .service.name -}}
  name: {{ .service.name }}-{{ include "workload.fullname" $ }}
  {{/* Otherwise set to port name */}}
  {{- else if .name -}}
  name: {{ .name }}-{{ include "workload.fullname" $ }}
  {{- else -}}
  {{/* Otherwise default to workload name */}}
  name: {{ include "workload.fullname" $ }}
  {{- end }}
  labels:
    {{- include "workload.labels" $ | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .service.type .serviceType }}
  ports:
    - port: {{ default .port .service.port }}
      targetPort: {{ default .name .containerPortNameOverride }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ default .name .service.name }}
  selector:
    {{- include "workload.selectorLabels" $ | nindent 4 }}
---
    {{- end }}
  {{- end}}
{{- end }}
