{{- if not .Values.persistence.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workload.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workload.serviceAccountName" . }}
      {{ if .Values.hostNetwork.enabled }}
      hostNetwork: true
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ default "TCP" .protocol }}
            {{- end }}
          {{- if .Values.health }}
            {{- if and (.Values.health.livenessProbe) (not (quote .Values.health.livenessProbe | empty)) }}
          livenessProbe:
              {{- toYaml .Values.health.livenessProbe | nindent 12 }}
            {{- end }}
            {{- if and (.Values.health.readinessProbe) (not (quote .Values.health.readinessProbe | empty)) }}
          readinessProbe:
              {{- toYaml .Values.health.readinessProbe | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- range .Values.volumes.host }}
            - name: {{ .name }}
              mountPath: {{ .containerPath.path }}
          {{- end }}
          {{- if .Values.env }}
          envFrom:
            - configMapRef:
                name: {{ include "workload.env-configMapName" . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{/* Add VPN sidecar if enabled */}}
      {{- if ((.Values.vpn).enabled) }}
        {{ include "gluetun.sidecar" . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # add additional volumes if vpn.enabled is true
      {{- if or ((.Values.vpn).enabled) ((.Values.volumes).host) }}
      volumes:
      {{- with .Values.volumes.host   }}
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{- if ((.Values.vpn).enabled) }}
        {{- include "gluetun.volume" . | nindent 8 }}
      {{ end }}
      {{- end }}
{{- end }}
